seed_everything_default: 7

trainer:
  accelerator: gpu
  strategy: ddp
  devices: 4  # hoặc "auto" nếu không chắc
  max_epochs: 400
  check_val_every_n_epoch: 2
  deterministic: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_ExpRate
        mode: max
        filename: "{epoch}-{step}-{val_ExpRate:.4f}"

model:
  d_model: 256
  growth_rate: 24
  num_layers: 16
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dc: 32
  dropout: 0.3
  vocab_size: 113
  cross_coverage: true
  self_coverage: true
  beam_size: 10
  max_len: 200
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  learning_rate: 1.0
  patience: 20
  milestones:
    - 300
    - 350

data:
  folder: data/crohme
  test_folder: 2014
  max_size: 320000
  scale_to_limit: true
  train_batch_size: 8
  eval_batch_size: 2
  num_workers: 5
  scale_aug: false
